baseURL = "https://front-end-blog.netlify.app/"
languageCode = "en-us"
title = "My New Hugogo Site"
enableRobotsTXT= true

[outputs]
home = ["HTML", "RSS"]

 
[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    noHl = false
    style = 'monokai'
    tabWidth = 4
